spring:
  application:
    name: data-status-evaluation
  profiles:
    group:
      dev: dev
      prod: prod
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: cubrid.jdbc.driver.CUBRIDDriver
    url: [url]
    username: [username]
    password: [password]

  jpa:
    hibernate:
#      ddl-auto: validate
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.CUBRIDDialect

  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: ABSOLUTE_PATH/upload

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 10

logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG
app:
  telnoSeed: ${SEED_KEY}
server:
  servlet:
    context-path: /dse
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: cubrid.jdbc.driver.CUBRIDDriver
    url: ${DSE_DB_URL}
    username: ${DSE_DB_USER}
    password: ${DSE_DB_PW}

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.CUBRIDDialect

  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      location: ${DSE_UPLOAD_PATH}

  mvc:
    hiddenmethod:
      filter:
        enabled: true
    format:
      date: yyyy-mm-dd
  main:
    allow-bean-definition-overriding: true
  session:
    store-type: jdbc
    timeout: 600
    jdbc:
      initialize-schema: never
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 10

logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG
app:
  telnoSeed: ${DSE_SEED_VALUE}

server:
  port: ${DSE_PORT}
  servlet:
    context-path: ${DSE_CONTEXT_PATH}